module.exports = [
  'Discussions allows community members to start conversations and ask questions without opening issues. Get started by toggling Discussions under Features.',
  ' This book is designed to introduce the reader to basic deep learning concepts and incorporate that knowledge into Angular 10 applications. It is intended to be a fast-paced introduction to some basic features of deep learning and an overview of several popular deep learning classifiers. The book includes code samples and numerous figures and covers topics such as Angular 10 functionality, basic deep learning concepts, classification algorithms, TensorFlow, and Keras. ',
  'Data structures provide a means to managing huge amounts of information such as large databases, using SEO effectively, and creating Internet/Web indexing services. This book is designed to present fundamentals of data structures for beginners using the Python programming language in a friendly, self-teaching, format. Practical analogies using real world applications are integrated throughout the text to explain technical concepts. The book includes a variety of end-of-chapter practice exercises, e.g., programming, theoretical, and multiple-choice.',
  'This book equips the reader with the rationale for vigorous testing of game software, how game testing and the tester fit into the game development process, practical knowledge of tools to apply to game testing, game tester roles and responsibilities, and the measurements to determine game quality and testing progress. The reader is taken step-by-step through test design and other QA methods, using real game situations. The book includes content for the latest console games and the new crop of touch, mobile, and social games that have recently emerged. A companion DVD contains the tools used for the examples in the book and additional resources such as test table templates and generic flow diagrams to get started quickly with any game test project. ',
  'This book covers the MATLAB syntax and the environment suitable for someone with no programming background. The first four chapters present information on basic MATLAB programming including computing terminology, MATLAB specific syntax and control structures, operators, arrays and matrices. The next cluster covers grouping data, working with files, making images, creating graphical user interfaces, experimenting with sound, and the debugging environment. The final three chapters contain case studies on using MATLAB and other tools and devices (e.g., Arduino, Linux, Git, Mex, etc.) ',
  'This updated bestseller provides an introduction to programming interactive computer graphics, with an emphasis on game development using DirectX 12. The book is divided into three main parts: basic mathematical tools, fundamental tasks in Direct3D, and techniques and special effects. It shows how to use new Direct12 features such as command lists, pipeline state objects, descriptor heaps and tables, and explicit resource management to reduce CPU overhead and increase scalability across multiple CPU cores. The book covers modern special effects and techniques such as hardware tessellation, writing compute shaders, ambient occlusion, reflections, normal and displacement mapping, shadow rendering, and character animation.',
  'This book is designed to introduce readers to an assortment of useful command-line utilities that can be combined to create simple, yet powerful shell scripts. While all examples and scripts use the "bash" command set, many of the concepts translate into other command shells (such as sh, ksh, zsh, and csh), including the concept of piping data between commands and the highly versatile sed and awk commands. Aimed at a reader relatively new to working in a bash environment, the book is comprehensive enough to be a good reference and teach a few new techniques to those who already have some experience with creating shell scripts. It contains a variety of code fragments and shell scripts for data scientists, data analysts, and other people who want shell-based solutions to "clean" various types of text files.'
];
